version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: heimdall-postgres
    environment:
      POSTGRES_DB: heimdall
      POSTGRES_USER: heimdall_user
      POSTGRES_PASSWORD: heimdall_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heimdall_user -d heimdall"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: heimdall-go-service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://heimdall_user:heimdall_password@postgres:5432/heimdall?sslmode=disable
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app

volumes:
  postgres_data: